/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.probanksystem;
import java.time.DateTimeException;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;

import javax.swing.JOptionPane;

/**
 *
 * @author Msi gl
 */
public class AccountOptions extends javax.swing.JFrame {

    /**
     * Creates new form AccountOptions
     */
    public AccountOptions() {
        initComponents();
       ///////////////////////////////////////////////////////////////////////
       ///////////////////////////////////////////////////////////////////////
       AccStatus.setVisible(true);
        BalanceDep.setVisible(false);
        Transfer.setVisible(false);
        Purchases.setVisible(false);
        UpdateUserInfo.setVisible(false);
        CCDep.setVisible(false);
        WithDrawBalance.setVisible(false);
        AccountName.setText(CheckingClass.getAccountName());
        AccountNumber.setText(String.valueOf(CheckingClass.getAccNumber()));
        Balance.setText(String.valueOf(CheckingClass.getBalance()));
        EmailAdress.setText(CheckingClass.getEmailAddress());
        Income.setText(String.valueOf(CheckingClass.getIncome()));
        PhoneNumber.setText(CheckingClass.getPhoneNumber());
        TypeOfAccount.setText(CheckingClass.VIPorStandard());
        
        if(CheckingClass.getBalance()> 500000){
            if(CheckingClass.getVIPCCBalance() == CheckingClass.getVIPCCLimit())
            {
            Indeptencey.setText("Not indebted");
            CheckingClass.RemainingdaysVIP=0;
             }
            else if(CheckingClass.daysBetween >120){
            Indeptencey.setText("indebted");
             }
            else{
            Indeptencey.setText("Not indebted");
             }
            CCLimit.setText(String.valueOf(CheckingClass.getVIPCCLimit()));
            CCBalance.setText(String.valueOf(CheckingClass.getVIPCCBalance()));
            RemainingDays.setText(String.valueOf(CheckingClass.RemainingdaysVIP));
            }
        else{
        if(CheckingClass.getCCBalance() == CheckingClass.getCCLimit())
        {
            CheckingClass.Remainingdays=0;
            Indeptencey.setText("Not indebted");
        }
        else if(CheckingClass.daysBetween > 60){
            Indeptencey.setText("indebted");
        }
        else{
            Indeptencey.setText("Not indebted");
        }
        CCLimit.setText(String.valueOf(CheckingClass.getCCLimit()));
        CCBalance.setText(String.valueOf(CheckingClass.getCCBalance()));
        RemainingDays.setText(String.valueOf(CheckingClass.Remainingdays));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CheckStatus = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BalanceDeposit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CCDeposit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TransferMoney = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Purchase = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        UpdateUser = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Withdraw = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BalanceDep = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        CurrentBalance = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        AmountDeposited = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CCDep = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        CurrentCCBalance = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        AmountDeposited1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Transfer = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        AnotherAccNumb = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        BalanceTransfer = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Purchases = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        CCBalance1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        PurchaseValue = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        DateOfPurchase = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        UpdateUserInfo = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        NewAccountName = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        NewPassword = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        NewEmailAddress = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        NewPhoneNumber = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        WithDrawBalance = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        CurrentBalance1 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        BalanceTaken = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        AccStatus = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AccountName = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        EmailAdress = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Balance = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Income = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        AccountNumber = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CCBalance = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CCLimit = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Indeptencey = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        RemainingDays = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TypeOfAccount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MMABank");

        CheckStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckStatusMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Check Status");

        javax.swing.GroupLayout CheckStatusLayout = new javax.swing.GroupLayout(CheckStatus);
        CheckStatus.setLayout(CheckStatusLayout);
        CheckStatusLayout.setHorizontalGroup(
            CheckStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckStatusLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CheckStatusLayout.setVerticalGroup(
            CheckStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        BalanceDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BalanceDepositMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Balance Deposit");

        javax.swing.GroupLayout BalanceDepositLayout = new javax.swing.GroupLayout(BalanceDeposit);
        BalanceDeposit.setLayout(BalanceDepositLayout);
        BalanceDepositLayout.setHorizontalGroup(
            BalanceDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BalanceDepositLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BalanceDepositLayout.setVerticalGroup(
            BalanceDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BalanceDepositLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        CCDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CCDepositMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CreditCard Deposit");

        javax.swing.GroupLayout CCDepositLayout = new javax.swing.GroupLayout(CCDeposit);
        CCDeposit.setLayout(CCDepositLayout);
        CCDepositLayout.setHorizontalGroup(
            CCDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CCDepositLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CCDepositLayout.setVerticalGroup(
            CCDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CCDepositLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        TransferMoney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransferMoneyMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Transfer Money");

        javax.swing.GroupLayout TransferMoneyLayout = new javax.swing.GroupLayout(TransferMoney);
        TransferMoney.setLayout(TransferMoneyLayout);
        TransferMoneyLayout.setHorizontalGroup(
            TransferMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferMoneyLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TransferMoneyLayout.setVerticalGroup(
            TransferMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransferMoneyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        Purchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PurchaseMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Purchase");

        javax.swing.GroupLayout PurchaseLayout = new javax.swing.GroupLayout(Purchase);
        Purchase.setLayout(PurchaseLayout);
        PurchaseLayout.setHorizontalGroup(
            PurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PurchaseLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PurchaseLayout.setVerticalGroup(
            PurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PurchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        UpdateUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateUserMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("UpdateUser Infromation");

        javax.swing.GroupLayout UpdateUserLayout = new javax.swing.GroupLayout(UpdateUser);
        UpdateUser.setLayout(UpdateUserLayout);
        UpdateUserLayout.setHorizontalGroup(
            UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        UpdateUserLayout.setVerticalGroup(
            UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Logout");

        javax.swing.GroupLayout LogoutLayout = new javax.swing.GroupLayout(Logout);
        Logout.setLayout(LogoutLayout);
        LogoutLayout.setHorizontalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogoutLayout.setVerticalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        Withdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WithdrawMouseClicked(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setText("Withdraw");

        javax.swing.GroupLayout WithdrawLayout = new javax.swing.GroupLayout(Withdraw);
        Withdraw.setLayout(WithdrawLayout);
        WithdrawLayout.setHorizontalGroup(
            WithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithdrawLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel41)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WithdrawLayout.setVerticalGroup(
            WithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithdrawLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheckStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BalanceDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CCDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(TransferMoney, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Purchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UpdateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Withdraw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(CheckStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BalanceDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CCDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TransferMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Purchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("Balance Deposit");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Current Balance:");

        CurrentBalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Amount Deposited:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Deposit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BalanceDepLayout = new javax.swing.GroupLayout(BalanceDep);
        BalanceDep.setLayout(BalanceDepLayout);
        BalanceDepLayout.setHorizontalGroup(
            BalanceDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BalanceDepLayout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BalanceDepLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(282, 282, 282))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BalanceDepLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(BalanceDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(BalanceDepLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BalanceDepLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(AmountDeposited, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(181, 181, 181))
        );
        BalanceDepLayout.setVerticalGroup(
            BalanceDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BalanceDepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BalanceDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BalanceDepLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(CurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BalanceDepLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BalanceDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmountDeposited, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setText("Credit Card Balance Deposit");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Current Credit Card Balance:");

        CurrentCCBalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Amount Deposited:");

        AmountDeposited1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountDeposited1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Deposit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CCDepLayout = new javax.swing.GroupLayout(CCDep);
        CCDep.setLayout(CCDepLayout);
        CCDepLayout.setHorizontalGroup(
            CCDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CCDepLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(234, 234, 234))
            .addGroup(CCDepLayout.createSequentialGroup()
                .addGroup(CCDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CCDepLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(CCDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CCDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AmountDeposited1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(CurrentCCBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(CCDepLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CCDepLayout.setVerticalGroup(
            CCDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CCDepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(CCDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(CurrentCCBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(CCDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmountDeposited1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setText("Transfer Balance Cash");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Account number of the required account:");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Amount of cash wanted to transfer:");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Transfer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TransferLayout = new javax.swing.GroupLayout(Transfer);
        Transfer.setLayout(TransferLayout);
        TransferLayout.setHorizontalGroup(
            TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel29)
                        .addComponent(jLabel30))
                    .addComponent(jLabel28)
                    .addGroup(TransferLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGap(33, 33, 33)
                .addGroup(TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BalanceTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnotherAccNumb, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TransferLayout.setVerticalGroup(
            TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnotherAccNumb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel31.setText("Purchase Operation");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("Current CreditCard Balance:");

        CCBalance1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("Purchase Value:");

        PurchaseValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseValueActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Date Of Purchase: (dd/MM/yyyy)");

        DateOfPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateOfPurchaseActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Purchase");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PurchasesLayout = new javax.swing.GroupLayout(Purchases);
        Purchases.setLayout(PurchasesLayout);
        PurchasesLayout.setHorizontalGroup(
            PurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PurchasesLayout.createSequentialGroup()
                .addGroup(PurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PurchasesLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(PurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PurchasesLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DateOfPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PurchasesLayout.createSequentialGroup()
                                .addGroup(PurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PurchasesLayout.createSequentialGroup()
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42))
                                    .addGroup(PurchasesLayout.createSequentialGroup()
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)))
                                .addGroup(PurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(PurchaseValue)
                                    .addComponent(CCBalance1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))))
                    .addGroup(PurchasesLayout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PurchasesLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel31)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        PurchasesLayout.setVerticalGroup(
            PurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PurchasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(PurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PurchaseValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateOfPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel35.setText("Update User Information");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setText("Name:");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setText("Password:");

        NewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPasswordActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setText("Email Adress:");

        NewEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewEmailAddressActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setText("Phone Number:");

        NewPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPhoneNumberActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Confirm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateUserInfoLayout = new javax.swing.GroupLayout(UpdateUserInfo);
        UpdateUserInfo.setLayout(UpdateUserInfoLayout);
        UpdateUserInfoLayout.setHorizontalGroup(
            UpdateUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateUserInfoLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(UpdateUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(UpdateUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateUserInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(UpdateUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateUserInfoLayout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateUserInfoLayout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))))
        );
        UpdateUserInfoLayout.setVerticalGroup(
            UpdateUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateUserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(UpdateUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(NewAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UpdateUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(NewPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UpdateUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(NewEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(NewPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel40.setText("Withdraw");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel42.setText("Current Balance:");

        CurrentBalance1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel43.setText("Amount Withdrawn:");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Withdraw");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WithDrawBalanceLayout = new javax.swing.GroupLayout(WithDrawBalance);
        WithDrawBalance.setLayout(WithDrawBalanceLayout);
        WithDrawBalanceLayout.setHorizontalGroup(
            WithDrawBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithDrawBalanceLayout.createSequentialGroup()
                .addGroup(WithDrawBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WithDrawBalanceLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(WithDrawBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(WithDrawBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BalanceTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CurrentBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(WithDrawBalanceLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WithDrawBalanceLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        WithDrawBalanceLayout.setVerticalGroup(
            WithDrawBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithDrawBalanceLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WithDrawBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(CurrentBalance1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(WithDrawBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        AccStatus.setPreferredSize(new java.awt.Dimension(917, 578));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Account Status");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Account Name:");

        AccountName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Email Address:");

        EmailAdress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Phone Number:");

        PhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Balance:");

        Balance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Income:");

        Income.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Account Number:");

        AccountNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("CreditCard Balance:");

        CCBalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("CreditCard Limit:");

        CCLimit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Indepted Status:");

        Indeptencey.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Remaining Days (Indebt):");

        RemainingDays.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Type Of Account:");

        TypeOfAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout AccStatusLayout = new javax.swing.GroupLayout(AccStatus);
        AccStatus.setLayout(AccStatusLayout);
        AccStatusLayout.setHorizontalGroup(
            AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccStatusLayout.createSequentialGroup()
                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccStatusLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AccStatusLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemainingDays, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AccStatusLayout.createSequentialGroup()
                            .addGap(176, 176, 176)
                            .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(44, 44, 44)
                            .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TypeOfAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                .addComponent(AccountName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmailAdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Income, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AccountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CCBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CCLimit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Indeptencey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(AccStatusLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(153, 153, 153))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        AccStatusLayout.setVerticalGroup(
            AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccStatusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Income, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Indeptencey, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeOfAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemainingDays, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BalanceDep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Purchases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CCDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Transfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(UpdateUserInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(WithDrawBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AccStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BalanceDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Purchases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CCDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Transfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(UpdateUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(WithDrawBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AccStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckStatusMouseClicked
        AccStatus.setVisible(true);
        BalanceDep.setVisible(false);
        Transfer.setVisible(false);
        Purchases.setVisible(false);
        UpdateUserInfo.setVisible(false);
        CCDep.setVisible(false);
        WithDrawBalance.setVisible(false);
        AccountName.setText(CheckingClass.getAccountName());
        AccountNumber.setText(String.valueOf(CheckingClass.getAccNumber()));
        Balance.setText(String.valueOf(CheckingClass.getBalance()));
        EmailAdress.setText(CheckingClass.getEmailAddress());
        Income.setText(String.valueOf(CheckingClass.getIncome()));
        PhoneNumber.setText(CheckingClass.getPhoneNumber());
        TypeOfAccount.setText(CheckingClass.VIPorStandard());
        
        if(CheckingClass.getBalance()> 500000){
            if(CheckingClass.getVIPCCBalance() == CheckingClass.getVIPCCLimit())
            {
            Indeptencey.setText("Not Indebt");
            CheckingClass.RemainingdaysVIP=0;
             }
            else if(CheckingClass.daysBetween >120){
            Indeptencey.setText("Indebt");
             }
            else{
            Indeptencey.setText("Not Indebt");
             }
            CCLimit.setText(String.valueOf(CheckingClass.getVIPCCLimit()));
            CCBalance.setText(String.valueOf(CheckingClass.getVIPCCBalance()));
            RemainingDays.setText(String.valueOf(CheckingClass.RemainingdaysVIP));
            }
        else{
        if(CheckingClass.getCCBalance() == CheckingClass.getCCLimit())
        {
            CheckingClass.Remainingdays=0;
            Indeptencey.setText("Not Indebt");
        }
        else if(CheckingClass.daysBetween > 60){
            Indeptencey.setText("Indebt");
        }
        else{
            Indeptencey.setText("Not Indebt");
        }
        CCLimit.setText(String.valueOf(CheckingClass.getCCLimit()));
        CCBalance.setText(String.valueOf(CheckingClass.getCCBalance()));
        RemainingDays.setText(String.valueOf(CheckingClass.Remainingdays));
        }
        
       
        

    }//GEN-LAST:event_CheckStatusMouseClicked

    private void BalanceDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BalanceDepositMouseClicked
         CurrentBalance.setText(String.valueOf(CheckingClass.getBalance()));
        AccStatus.setVisible(false); 
        BalanceDep.setVisible(true);
         Transfer.setVisible(false);
        Purchases.setVisible(false);
        UpdateUserInfo.setVisible(false);
        CCDep.setVisible(false);
        WithDrawBalance.setVisible(false);
    }//GEN-LAST:event_BalanceDepositMouseClicked

    private void TransferMoneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferMoneyMouseClicked
        Transfer.setVisible(true);
         BalanceDep.setVisible(false);
         AccStatus.setVisible(false);
         Purchases.setVisible(false);
        UpdateUserInfo.setVisible(false);
        CCDep.setVisible(false);
        WithDrawBalance.setVisible(false);
    }//GEN-LAST:event_TransferMoneyMouseClicked

    private void PurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PurchaseMouseClicked
         if(CheckingClass.getBalance()<500000 && CheckingClass.getBalance()>=0){
        CCBalance1.setText(String.valueOf(CheckingClass.getCCBalance()));
         }
        else{
        CCBalance1.setText(String.valueOf(CheckingClass.getVIPCCBalance()));
        }
        Purchases.setVisible(true);
        Transfer.setVisible(false);
         BalanceDep.setVisible(false);
         AccStatus.setVisible(false);
         UpdateUserInfo.setVisible(false);
         CCDep.setVisible(false);
         WithDrawBalance.setVisible(false);
    }//GEN-LAST:event_PurchaseMouseClicked

    private void UpdateUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateUserMouseClicked
        UpdateUserInfo.setVisible(true);
         Transfer.setVisible(false);
         BalanceDep.setVisible(false);
         AccStatus.setVisible(false);
         Purchases.setVisible(false);
         CCDep.setVisible(false);
         WithDrawBalance.setVisible(false);
    }//GEN-LAST:event_UpdateUserMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(AmountDeposited.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Enter all the fields");
        }
        else{
            try{
                String AmountDep=AmountDeposited.getText();
                double AmountDeposited=Double.parseDouble(AmountDep);
                if(AmountDeposited >= 0){
                    CheckingClass.Depositbalance(AmountDeposited);
                    JOptionPane.showMessageDialog(null, "Amount Deposited: "+AmountDep);
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "Enter correct amount of money");
                }
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Please enter correct number not text!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AmountDeposited1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountDeposited1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountDeposited1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(AmountDeposited1.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Enter the missing field");
        }
        else{
            try{
                String AmountDep=AmountDeposited1.getText();
                double AmountDeposited=Double.parseDouble(AmountDep);
                if(CheckingClass.getBalance()<500000 && CheckingClass.getBalance()>0){
                    if(AmountDeposited >=0){
                        if(AmountDeposited+CheckingClass.getCCBalance() <=CheckingClass.getCCLimit()){
                            CheckingClass.DepositCCbalance(AmountDeposited);
                            JOptionPane.showMessageDialog(null, "Amount Deposited in CreditCard: "+AmountDep);
                            
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "You can't exceed the Creditcard limit, Try again");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Enter correct amount of money");
                    }
                }
                else{
                    if(AmountDeposited >=0){
                        if(AmountDeposited+CheckingClass.getVIPCCBalance() <= CheckingClass.getVIPCCLimit()){
                            CheckingClass.DepositVIPCCbalance(AmountDeposited);
                            JOptionPane.showMessageDialog(null, "Amount Deposited in CreditCard: "+AmountDep);
                            
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "You can't exceed the Creditcard limit, Try again");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Enter correct amount of money");
                    }
                }
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Please enter correct number not text!");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(AnotherAccNumb.getText().isEmpty() || BalanceTransfer.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Enter all the fields");
        }
        else{
            try{
                String scndAccountnumber=AnotherAccNumb.getText();
                String Balancetransfer=BalanceTransfer.getText();
                int x=Integer.parseInt(scndAccountnumber);
                double Balance=Double.parseDouble(Balancetransfer);
                if(Balance>0 && Balance<=CheckingClass.getBalance()){
                    CheckingClass.TransferCash(x,Balance);
                    JOptionPane.showMessageDialog(null, "Successfully Transfered.");
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "Insufficient funds!");
                }
            }

            catch(NullPointerException e){
                JOptionPane.showMessageDialog(null, "The account number entered doesn't exist!");
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Please enter correct number not text!");
            }
            catch(ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null,"The account number entered doesn't exist");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PurchaseValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PurchaseValueActionPerformed

    private void DateOfPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateOfPurchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateOfPurchaseActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(PurchaseValue.getText().isEmpty() || DateOfPurchase.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Enter all the fields");
        }
        if(CheckingClass.getBalance() >500000){
            if(CheckingClass.getVIPCCBalance() == CheckingClass.getVIPCCLimit())
            {
                try{
                    String PurchaseVal=PurchaseValue.getText();
                    String DateIndept=DateOfPurchase.getText();
                    Double PurchaseValuel=Double.parseDouble(PurchaseVal);
                    CheckingClass.DateStatusStandard(DateIndept);
                    if(PurchaseValuel<0){
                        JOptionPane.showMessageDialog(null, "Enter a correct amount of money");
                    }
                    else if( PurchaseValuel > CheckingClass.getVIPCCBalance() ){
                        JOptionPane.showMessageDialog(null,"You don't have sufficient funds!");
                    }
                    else{
                        CheckingClass.PurchaseValVIP(PurchaseValuel);
                        JOptionPane.showMessageDialog(null,"Operation Successful");
                        
                    }
                }
                catch(DateTimeParseException e){
                    JOptionPane.showMessageDialog(null,"Please enter correct format of date!");
                }
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"Please enter correct number not text!");
                }
            }
            else{
                try{
                    String PurchaseVal=PurchaseValue.getText();
                    Double PurchaseValuel=Double.parseDouble(PurchaseVal);
                    if(PurchaseValuel<0){
                        JOptionPane.showMessageDialog(null, "Enter a correct amount of money");
                    }
                    else if( PurchaseValuel> CheckingClass.getVIPCCBalance() ){
                        JOptionPane.showMessageDialog(null,"You don't have sufficient funds!");
                    }
                    else{
                        CheckingClass.PurchaseValVIP(PurchaseValuel);
                        JOptionPane.showMessageDialog(null,"Operation Successful");
                        
                    }
                }
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"Please enter correct number not text!");
                }
            }
        }

        else if (CheckingClass.getBalance() <=500000 && CheckingClass.getBalance()>0)
        {   if(CheckingClass.getCCBalance() == CheckingClass.getCCLimit())
            try{
                String PurchaseVal=PurchaseValue.getText();
                String DateIndept=DateOfPurchase.getText();
                Double PurchaseValuel=Double.parseDouble(PurchaseVal);
                CheckingClass.DateStatusStandard(DateIndept);
                if(PurchaseValuel<0){
                    JOptionPane.showMessageDialog(null, "Enter a correct amount of money");
                }
                else if( PurchaseValuel> CheckingClass.getCCBalance() ){
                    JOptionPane.showMessageDialog(null,"You don't have sufficient funds!");
                }
                else{
                    CheckingClass.PurchaseVal(PurchaseValuel);
                    JOptionPane.showMessageDialog(null,"Operation Successful");
                    
                }
            }
            catch(DateTimeParseException e){
                JOptionPane.showMessageDialog(null,"Please enter correct format of date!");
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Please enter correct number not text!");
            }

            else{
                try{
                    String PurchaseVal=PurchaseValue.getText();
                    Double PurchaseValuel=Double.parseDouble(PurchaseVal);
                    if(PurchaseValuel<0){
                        JOptionPane.showMessageDialog(null, "Enter a correct amount of money");
                    }
                    else if( PurchaseValuel> CheckingClass.getCCBalance() ){
                        JOptionPane.showMessageDialog(null,"You don't have sufficient funds!");
                    }
                    else{
                        CheckingClass.PurchaseVal(PurchaseValuel);
                        JOptionPane.showMessageDialog(null,"Operation Successful");
                        
                    }
                }
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null,"Please enter correct number not text!");
                }
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void NewPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPhoneNumberActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if( NewAccountName.getText().isEmpty() && NewPassword.getText().isEmpty() &&
            NewEmailAddress.getText().isEmpty() && NewPhoneNumber.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter atleast one field!");
        }

        else{
            if(!NewAccountName.getText().isEmpty()){
                String name=NewAccountName.getText();
                CheckingClass.setAccountName(name);
            }
            if(!NewPassword.getText().isEmpty()){
                String password=NewPassword.getText();
                CheckingClass.setPassword(password);
            }
            if(!NewEmailAddress.getText().isEmpty()){
                String EmailAddress=NewEmailAddress.getText();
                CheckingClass.setEmaiLAddress(EmailAddress);
            }
            if(!NewPhoneNumber.getText().isEmpty()){
                String PhoneNumber=NewPhoneNumber.getText();
                CheckingClass.setPhoneNumber(PhoneNumber);
            }
            if(!CheckingClass.checkPassword()){
                JOptionPane.showMessageDialog(null, "The password is too short, Please try again");
            }
            else if(!CheckingClass.checkEmail()){
                JOptionPane.showMessageDialog(null, "The email you entered isn't correct, Please try again");
            }
            else if(!CheckingClass.checkPhonenumber()){
                JOptionPane.showMessageDialog(null, "Enter a correct phone number, Please try again");
            }

            else{
                JOptionPane.showMessageDialog(null, "Account Succesfully Updated");
                
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void NewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPasswordActionPerformed

    private void CCDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCDepositMouseClicked
       if(CheckingClass.getBalance()<500000 && CheckingClass.getBalance()>=0){
        CurrentCCBalance.setText(String.valueOf(CheckingClass.getCCBalance()));
         }
        else{
        CurrentCCBalance.setText(String.valueOf(CheckingClass.getVIPCCBalance()));
        }
        CCDep.setVisible(true);
        AccStatus.setVisible(false); 
        BalanceDep.setVisible(false);
        Transfer.setVisible(false);
        Purchases.setVisible(false);
        UpdateUserInfo.setVisible(false);
        WithDrawBalance.setVisible(false);
    }//GEN-LAST:event_CCDepositMouseClicked

    private void WithdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WithdrawMouseClicked
       CurrentBalance1.setText(String.valueOf(CheckingClass.getBalance()));
        WithDrawBalance.setVisible(true);
        UpdateUserInfo.setVisible(false);
         Transfer.setVisible(false);
         BalanceDep.setVisible(false);
         AccStatus.setVisible(false);
         Purchases.setVisible(false);
         CCDep.setVisible(false);
    }//GEN-LAST:event_WithdrawMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(BalanceTaken.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Enter all the fields!");
        }
        else{
            try{
                String Balancetaken=BalanceTaken.getText();
                double Balancetaken2=Double.parseDouble(Balancetaken);
                if(Balancetaken2 >=0){
                    if(Balancetaken2 <= CheckingClass.getBalance() ){
                        CheckingClass.Withdrawbalance(Balancetaken2);
                        JOptionPane.showMessageDialog(null, "Amount Withdrawn: "+Balancetaken2);
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "You don't have enough money!");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Enter correct amount of money!");
                }
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Please enter correct number not text!");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void NewEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewEmailAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccStatus;
    private javax.swing.JLabel AccountName;
    private javax.swing.JLabel AccountNumber;
    private javax.swing.JTextField AmountDeposited;
    private javax.swing.JTextField AmountDeposited1;
    private javax.swing.JTextField AnotherAccNumb;
    private javax.swing.JLabel Balance;
    private javax.swing.JPanel BalanceDep;
    private javax.swing.JPanel BalanceDeposit;
    private javax.swing.JTextField BalanceTaken;
    private javax.swing.JTextField BalanceTransfer;
    private javax.swing.JLabel CCBalance;
    private javax.swing.JLabel CCBalance1;
    private javax.swing.JPanel CCDep;
    private javax.swing.JPanel CCDeposit;
    private javax.swing.JLabel CCLimit;
    private javax.swing.JPanel CheckStatus;
    private javax.swing.JLabel CurrentBalance;
    private javax.swing.JLabel CurrentBalance1;
    private javax.swing.JLabel CurrentCCBalance;
    private javax.swing.JTextField DateOfPurchase;
    private javax.swing.JLabel EmailAdress;
    private javax.swing.JLabel Income;
    private javax.swing.JLabel Indeptencey;
    private javax.swing.JPanel Logout;
    private javax.swing.JTextField NewAccountName;
    private javax.swing.JTextField NewEmailAddress;
    private javax.swing.JTextField NewPassword;
    private javax.swing.JTextField NewPhoneNumber;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JPanel Purchase;
    private javax.swing.JTextField PurchaseValue;
    private javax.swing.JPanel Purchases;
    private javax.swing.JLabel RemainingDays;
    private javax.swing.JPanel Transfer;
    private javax.swing.JPanel TransferMoney;
    private javax.swing.JLabel TypeOfAccount;
    private javax.swing.JPanel UpdateUser;
    private javax.swing.JPanel UpdateUserInfo;
    private javax.swing.JPanel WithDrawBalance;
    private javax.swing.JPanel Withdraw;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
